### PR TITLE
Accessibility

### PR DESCRIPTION
**Pull request by Ellyboi**
Checks are done to the following sections below:
- Page title - Adjusted
- Image text alternative - No issue found
- Text heading - no issues found
- color contrast - no issues found
- Resize - No issue found
- Moving content - no issue found
- Multimedia - Adjusted
- Basic structure of the page - no issues found

### CODE REVIEW

**Comment by Ellyboi** [comment]
Checks are done to the following sections below:
- Page title - Adjusted
- Image text alternative - Adjusted
- Text heading - no issues found
- color contrast - no issues found
- Resize - No issue found
- Moving content - no issue found
- Multimedia - Adjusted
- Basic structure of the page - no issues found

Adjusted code link:  https://github.com/Ellyboi/Desktop-portfolio-website/blob/3d0ae4c6661e7c076a4d9a2041b878c0d2dacbc6/index.html#L47-L284

**Review by jerryowusu — CHANGES_REQUESTED** [review]
Hi Team, 

Good job so far!
Your project is looking fantastic so far :star_struck: 

However, there are few changes you need to make in order to move on to the next level :sunglasses:

almost-there-reach


## Highlights
All linters are passing :heavy_check_mark: 
Great effort in this milestone :heavy_check_mark: 

## Required Changes ♻️

- [ ] Some images have empty alt text. Kindly check and add alt text values for the images on lines 47-51 and 280-284.  Since they are not for decorative purposes, they need to have values to aid accessibility readers and people who turn off images to speed up downloads or save bandwiths. :wink: 
- [ ] As per the project requirements, kindly provide links to all the changes/adjustment you made in the pull request. You can follow [this link](http://www.chasewoodford.com/blog/linking-highlighted-lines-code-github/#:~:text=To%20link%20to%20multiple%20lines,php%23L117%2DL148) for more information on how to do it. :stuck_out_tongue_winking_eye: 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Olamarx — APPROVED** [review]
Hi @Ellyboi, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Linters passed ✔️ 
- alt tags ✔️ 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by adel-gu — COMMENTED** [review]
# Status: INVALID ❌

**Hi @Ellyboi 👋🏼** 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that uses a PR for a different milestones.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by joskalenda — COMMENTED** [review]
| STATUS: APPROVED ✅ |
|------------------------|
| Hi @Ellyboi , 🥰|
| Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: Congratulations! 🎉  |
|  |


---------
### Optional suggestions

> _Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

### Cheers and Happy coding!👏👏👏
-------
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me(@joskalenda) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
